stages:
    - build_image

Build_Image:
    stage: build_image
    image: docker:19.03.15
    variables:
        DOCKER_TLS_CERTDIR: ""
        DOCKER_HOST: tcp://localhost:2375/
    services:
        - docker:19.03.15-dind
    script:
        - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
        - docker build --network host -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} .
        - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}

